name: Bug Report
description: Use this issue template when report bugs.
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Describe the bug
    validations:
      required: true

  - type: textarea
    attributes:
      label: To Reproduce
      value: |
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshots
    validations:
      required: false

  - type: dropdown
    attributes:
      label: OS
      multiple: true
      options:
        - label: Windows
        - label: Mac
        - label: Linux

  - type: dropdown
    attributes:
      label: Browser
      multiple: true
      options:
        - label: Google Chrome
        - label: Mozilla Firefox

  - type: textarea
    attributes:
      label: Additional context
    validations:
      required: false
