name: Feature Request
description: Use this issue template when request features.
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Describe the solution you'd like"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Describe alternatives you've considered"
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
    validations:
      required: false
